### ISSUE TITLE
Testing load based on time and steps

### ISSUE THREAD

**Issue by pesterev** [soramitsu/iroha2-longevity-load-rs#71]
According to [this issue](https://github.com/soramitsu/iroha2-longevity-load-rs/issues/69), we should add a step-based testing load.

My suggestion is to enhance the `oneshot` command:
- [ ] [Perform a pool of operations concurrently.](https://github.com/soramitsu/iroha2-longevity-load-rs/issues/76)
- [ ] [Perform in several steps.](https://github.com/soramitsu/iroha2-longevity-load-rs/issues/77)
- [ ] [Timeout for every step.](https://github.com/soramitsu/iroha2-longevity-load-rs/issues/78)
- [ ]  [Action on errors.](https://github.com/soramitsu/iroha2-longevity-load-rs/issues/73)

**Comment by timofeevmd** [comment]
explanations for the first two paragraphs

At the first stage, I enter 60 (in the context of the Ultimate Thread Group meter) parallel operations for 10 seconds

Each operation, which includes a sequence of transactions, of the first stage will be performed cyclically for 610 seconds independently of each other

<img width="1676" alt="Screenshot 2023-06-14 at 13 27 33" src="https://github.com/soramitsu/iroha2-longevity-load-rs/assets/47450344/ba9ec236-307f-4798-8c44-1a2d0531729e">
